apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-client-pvc
  namespace: nfs-testing
spec:
  storageClassName: nfs-client-dummy-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
