apiVersion: v1
kind: Service
metadata:
  labels:
    app: nfssrvr
  name: nfs-server
  namespace: nfs-testing
spec:
  type: LoadBalancer
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    app: nfssrvr
