apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-client-pv
spec:
  storageClassName: nfs-client-dummy-sc
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: "XX.XX.XX.XX" # "Populate with IP Address from NFS server export"
    path: "/exports"
