apiVersion: v1
kind: Pod
metadata:
  name: busybox-hrbr-no-secret
  namespace: default
  labels:
    app: busybox-hrbr-no-secret
spec:
  containers:
  - name: busybox
    image: 10.203.182.134/cormac-ns/busybox:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: Always
  restartPolicy: Always
